### ISSUE TITLE
Host it remotely for iterative modeling

### ISSUE THREAD

**Issue by haz** [AI-Planning/p4pp#2]
Students can submit repeatedly and get the plan that failed so they can improve.

**Comment by haz** [comment]
Currently testing live with my class (cf. #7 )

**Comment by haz** [comment]
This is pretty much done & working. Including a protocol for cool-down just like the original online solver (essential, since correct solutions on larger instances can be quite the challenge).

@nirlipo Want to have a look?

**Comment by nirlipo** [comment]
Nice feature! do you have a url with a session to see it in action?

**Comment by haz** [comment]
I'll spin it up again to show you -- will send the session link as a DM, since I'd rather not have assignment solutions floating around.

Any other instructors that find this, just let me know if you'd like access.
